# TODO: 'schedules' will need to be updated for months that have 5 Thursdays, or if next meeting date is different than normal.

name: Schedule monthly TAC meetings
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: wesleytodd/meeting-maker@v0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        schedules: 2020-09-10T17:00:00.0Z/P4W
        createWithin: P1D
        issueTitle: "TAC Meeting <%= date.toFormat('yyyy-MM-dd') %>"
        agendaLabel: meeting-agenda
    - uses: timheuer/issue-notifier@v1.0.2
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      with:
        fromMailAddress: 'tac@openmainframeproject.org'
        toMailAddress: 'omp-technical@lists.openmainframeproject.org'
        subject: 'TAC meeting agenda for today'
        labelsToMonitor: 'meeting'
        verbose: true
